; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
extra_configs = platformio_override.ini
default_envs = um_pros3


[env:um_pros3]
platform = espressif32
board = um_pros3
framework = arduino
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
    https://github.com/sparkfun/SparkFun_Qwiic_OTOS_Arduino_Library.git
    https://github.com/PaulStoffregen/Encoder
    ; https://github.com/stm32duino/VL53L4CX
    ; https://github.com/luksal/ESP32-DMX.git
    stm32duino/STM32duino VL53L4CX @ ^1.1.0
    https://github.com/stm32duino/ISM330DLC.git

    ; um_pros3/ESP32-DMX-RX
    ; sparkfun/SparkFun ESP32 DMX @ ^1.1.0
    ; arduino-libraries/ArduinoDMX@^1.0.1
    ; adafruit/Adafruit VL53L4CX
    ; 6886
    ; adafruit/Adafruit BusIO
    ; sparkfun/SparkFun Qwiic Optical Tracking Odometry Sensor PAA5160E1@^1.0.0
    https://github.com/sparkfun/SparkFun_Qwiic_OTOS_Arduino_Library.git
monitor_speed = 115200
; monitor_port = /dev/ttyACM1
# do not add upload port here; make a copy of "SAMPLE_platformio_override.ini"
# and name it "platformio_override.ini" and add the field there
