; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
extra_configs = platformio_override.ini
default_envs = um_pros3


[env:um_pros3]
platform = espressif32
board = um_pros3
framework = arduino
lib_deps = 
    https://github.com/sparkfun/SparkFun_Qwiic_OTOS_Arduino_Library.git
    https://github.com/PaulStoffregen/Encoder
    https://github.com/stm32duino/VL53L4CX
monitor_speed = 115200

# do not add upload port here; make a copy of "SAMPLE_platformio_override.ini"
# and name it "platformio_override.ini" and add the field there
